apiVersion: v1
kind: Config
clusters:
- name: ch1-cluster
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlakNDQVIrZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWtNU0l3SUFZRFZRUUREQmx5YTJVeUxYTmwKY25abGNpMWpZVUF4Tnpjek9USXdPVGt4TUI0WERUSTJNRE14T1RFeE5EazFNVm9YRFRNMk1ETXhOakV4TkRrMQpNVm93SkRFaU1DQUdBMVVFQXd3WmNtdGxNaTF6WlhKMlpYSXRZMkZBTVRjM016a3lNRGs1TVRCWk1CTUdCeXFHClNNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJEekdva005S0RQaXc1TGRWeFNMaXlraVlQMlJoQmZDMWJPMFBnd2YKZW9nMkpnaDJzVUl6bE1va3JCUW10Z1RaWEh2S1o1cVUzOFFSYlhTbVpQN2hBMitqUWpCQU1BNEdBMVVkRHdFQgovd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCUWhNQjhmeTVLb3dyckhNOGl5CnpBcUN3c28xZlRBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQWtSVGFkRWpUbENaaW5VZWhyV1BZZnRzN0lsbnkKcFNRNnVJVnYxYUwxZ21zQ0lRQzh1THVFZTZteTFGMTFGalh0YXUySkZoM2hhVTA0VHR3VjZkNVFnckZzMnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://103.171.92.247:6443

users:
- name: ch1-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjZuN1kxRzdaNm1XLUlZS2plenJteWZpSXhvZGlFc1lXLUFob3U2M1l0X00ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJya2UyIl0sImV4cCI6MTc3NDQxMzUzOCwiaWF0IjoxNzc0NDA5OTM4LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbCIsImp0aSI6ImM0MGRjYmFlLTIyMGUtNDJkOS1hOTIzLTc3YTFlYzI2MDg5NyIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoiY2gxIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImNoMS11c2VyIiwidWlkIjoiNzEwZTUyYzEtMmFlYS00ZmExLTkwNTQtYzQyZTFlZWU2MzA5In19LCJuYmYiOjE3NzQ0MDk5MzgsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjaDE6Y2gxLXVzZXIifQ.YvgaEw8N_MlhhpbLUotuu-kx2sEqKKUdTK3CHmGivaffeT25avCNeCt3B5pG2YW6J3QSubCE0QgWP23iCFa4Loy6gtH6mdSz3LqKZFYnb8QSh5arykyp7ayXzRfjKuGG8upFxYvKqyofn-ftztvk2KIsDtBxzN7onbCtnQcp7sMVOd44n904frFsQ8jpVXfZ3VGrnXe1JPTjWbFNK4JM9qJqTX5jTOcb2FExm6qDsIj7EV6kbkvk7rm-XM32hXvcpRhygIhNtfXzaCkjFZeTw15t-IimbduCt26w_Vn7pzHxbyN1MzpgSHX7enASiX3l0ltR4RNa5gpYVSpPNqNQrA

contexts:
- name: ch1-context
  context:
    cluster: ch1-cluster
    user: ch1-user
    namespace: ch1

current-context: ch1-context
