apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default # Thay đổi tên namespace tương ứng nếu cần
imagePullSecrets:
- name: registry-secret # Phải trùng với tên Secret bạn đã tạo

