apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-gitlab-secret
spec:
  rules:
  - name: sync-image-pull-secret
    match:
      any:
      - resources:
          kinds:
          - Namespace
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
          - kube-public
          - kube-node-lease
          - kyverno
          - default # Không copy đè lên chính nó
          - longhorn-system
          - cert-manager
          - monitoring
    generate:
      apiVersion: v1
      kind: Secret
      name: gitlab-registry-secret
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        namespace: default
        name: gitlab-registry-secret
